# Generated by Django 5.1.3 on 2024-12-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagename', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
